### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by gdelab** [klattmose/CookieClickerModManager#11]
I have installed the extension on Firefox
I have added a few mods, including CookieMonster and HortiCookie for instance.
I have clicked "load" in the extension's options.

When I open the game I do not see the cookie in the url nor any change that these mods could have added

**Comment by klattmose** [comment]
The only thing I know that would prevent it from appearing in the url bar is if the extension is disabled. Can you check that it's enabled?

![image](https://github.com/klattmose/CookieClickerModManager/assets/4196664/284a7d12-755d-4cb2-9e02-4e1eda965dbd)

**Comment by gdelab** [comment]
yes it is 

![image](https://github.com/klattmose/CookieClickerModManager/assets/25060504/bb58e9eb-aa93-4b6b-9541-720ac819f802)
![image](https://github.com/klattmose/CookieClickerModManager/assets/25060504/cfd2a01b-33fb-4ce4-a273-588c0a9663a4)
![image](https://github.com/klattmose/CookieClickerModManager/assets/25060504/5eb7db6b-2639-4399-8b19-a9c5a1b9120a)

**Comment by klattmose** [comment]
Why is there `?_r=1.af662f etc...` at the end of the url? That seems to be the issue (if I add that on mine, the extension stops for me as well). I think the extra text string is throwing off the url pattern matcher.

**Comment by gdelab** [comment]
don't know what it is, the cookie appears if i remove it, thanks :)
