### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by idK1234464485454** [klattmose/CookieClickerModManager#15]
I now understand how to use it  but is there anyway of getting a URL for something like cookistocker on pastebin I am new to doing this and I tried pasting the url for the raw code but that didn't work which seems obvious. So my question is how do I get an add-on that doesn't have a url linked to it? Here is the link to the mod (https://pastebin.com/raw/8qsFdMRn) and another same thing that isn't raw (https://pastebin.com/8qsFdMRn) when I paste this into the URL box on the mod manager doesn't work.

**Comment by klattmose** [comment]
Looks like it's an issue with Pastebin. When the file is requested, one of the response headers is `content-type: text/plain`. The browser thinks it's not Javascript, so it doesn't try to run it.

**Comment by idK1234464485454** [comment]
Alright thank you for answering my question. Sorry for any wasted time.
