### ISSUE TITLE
Wont load mods

### ISSUE THREAD

**Issue by KooKooGH** [klattmose/CookieClickerModManager#16]
After trying all day it just wont load any mods. I tried using the eu version and orteil.dashnet and still nothing! I tried loading one mod and so on, but still nothing :( is there anyway to fix this? Im using a macbook air with chrome installed with the extension on and active

**Comment by KooKooGH** [comment]
javascript:(function () {Game.LoadMod('https://cdn.jsdelivr.net/ghAncyker/Crustulum/Crustulum.js')}()); ive tried alone

ive tried javascript:Game.LoadMod("https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js"); alone

**Comment by KooKooGH** [comment]
2 errors: javascript:Game.LoadMod("https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js");?v=1698457739951 
        
        
       Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
and
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently when loading cookie monster only

but when using crustulm with the mod manager i get a 404 error but when in the console and putting the mod in it works fine and same with cookie monster

**Comment by klattmose** [comment]
Don't put any Javascript in the URL box, just the URL of the mod you want.

**Comment by KooKooGH** [comment]
worked thanks a bunch :)
