### ISSUE TITLE
chrome

### ISSUE THREAD

**Issue by EdDeNtEr** [klattmose/CookieClickerModManager#4]
im getting a 404 on the chrome version

**Comment by klattmose** [comment]
Google decided to be a fuck and take it down for having a minified third party CSS file. I've rectified that, but now I'm waiting on them to approve it (going on 2 days now). I'll close this issue when it gets approved.

**Comment by EdDeNtEr** [comment]
Allright no worries. I just thought i should bring it to your attention.
