### ISSUE TITLE
Does not work on the new Cookie Clicker Website

### ISSUE THREAD

**Issue by ghost** [klattmose/CookieClickerModManager#5]
Since the Cookie Clicker Website has moved domains this extension does not work properly

New : 
https://cookieclicker.eu/cookieclicker/
https://cookieclicker.eu/cookieclicker/beta

Old : 
http://orteil.dashnet.org/cookieclicker/ 
http://orteil.dashnet.org/cookieclicker/beta

Note :
I don't think you shouldn't remove the old domains because they are still functional

**Comment by klattmose** [comment]
Who told you that the game moved domains? As far as I know the correct site is still https://orteil.dashnet.org/cookieclicker/

**Comment by ghost** [comment]
If you check the official discord or ortiels tumblr he said the site moved

Edit : Both work properly but one will not be updated more I believe

**Comment by klattmose** [comment]
Do you have a link to the tumblr post where he said this?

**Comment by ghost** [comment]
[https://orteil42.tumblr.com/post/185795521945/orteil42-some-shenanigans-happening-with-our](url)
Here is the best one I found but I am sure it is on the official dashnet forums discord server. Here is the link to the message by opti : [https://discordapp.com/channels/412363381891137536/412369840586752000/601087534520598544](url)

**Comment by klattmose** [comment]
Found the discord message. I never saw it on the subreddit, which is where I focus most of my attention. I have the change made and a new version uploaded, but it will take some time for Google to approve it and let it go live. Firefox is faster, so I do that one second.

**Comment by ghost** [comment]
Ok, thank you!
