### ISSUE TITLE
UI Broken on Edge Dev

### ISSUE THREAD

**Issue by RuinTD** [klattmose/CookieClickerModManager#6]
The UI is broken on Microsoft Edge Dev (92.0.878.0). Clicking the settings button fixes the UI until you close it.
![image](https://user-images.githubusercontent.com/1149870/117529642-ddbbea80-af95-11eb-917e-4ece62d1943f.png)

**Comment by klattmose** [comment]
Cookie Clicker Mod Manager is only supported for Chrome and Firefox

**Comment by RuinTD** [comment]
Microsoft Edge is based on Chrome. I downloaded it from the Chrome Web Store.

**Comment by shawngmc** [comment]
I have the same issue in Chrome 91.0.4472.77.

Interestingly, if I click the gear icon, the UI seems to fix itself (first in the settings section, then in the main UI when I click back).

If I close the extension UI and re-show it, the same glitch occurs.

I'm wondering if the issue might be with the UI's size when the extension is first shown?

**Comment by RuinTD** [comment]
As I said, Microsoft Edge is based on Chromium. c:
