### ISSUE TITLE
Cant load CookieMonster addon with CCSE

### ISSUE THREAD

**Issue by OfficialZygorg** [klattmose/CookieClickerModManager#8]
![image](https://user-images.githubusercontent.com/43007952/132398088-5ca4c93d-a589-4aec-962e-45ed2f653959.png)

**Comment by OfficialZygorg** [comment]
Also, reloading the page does this
![image](https://user-images.githubusercontent.com/43007952/132398228-8aac4324-a9d9-489f-9cfa-c48e2bfef51b.png)

**Comment by OfficialZygorg** [comment]
This is when it loads correctly (at the moment, loading correctly has a bad rng)
![image](https://user-images.githubusercontent.com/43007952/132398548-a969e3f5-161d-4001-88fa-cbace9d191eb.png)

**Comment by OfficialZygorg** [comment]
You can "fix" this manually on the mod manager (google chrome) by disabling CookieMonster mod, reloading the page and loading the mod, because it tries to load the mod, before all the CCSE based mods load

**Comment by klattmose** [comment]
Version 1.4.0 will now load the mods in sequence by default (previously it would load asynchronously, with mods higher in the load order merely having a small time advantage). Putting CCSE at the top and CookieMonster at the bottom will let CCSE finish its injections before CookieMonster wraps the functions.
